### ISSUE TITLE
Sending JSON in the request body

### ISSUE THREAD

**Issue by volkanunsal** [mwunsch/weary#9]
I noticed that the current way of sending parameters is a query string. This is a problem for me since my service only accepts JSON objects. Any client library I build would need to support arguments as JSON or convert them into JSON before sending them to the service.

**Comment by jjwilliams** [comment]
So how does resource.required and resource.optional work with this?

**Comment by mwunsch** [comment]
@jjwilliams It doesn't. Don't use `optional` or `required` if you're using json in the request body. They are mutually exclusive, since in the case of a POST or PUT request the parameters will be sent in the body as though from a HTML form. If you need to have URL query parameters, attach those in the url without the use of `optional` and `required`.
